name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: actions/setup-dotnet@v1  
    - name: Build   
      run:  dotnet build 
    - name: Test
      run:  dotnet test
      working-directory: DotnetTemplate.Web
    - name: BuildTypescript
      run:  npm install
      working-directory: DotnetTemplate.Web
    - name: Linter
      run:  npm run lint
      working-directory: DotnetTemplate.Web
    - name: TestTypescript
      run:  npm t
      working-directory: DotnetTemplate.Web
      
    